### ISSUE TITLE
баги /js

### ISSUE THREAD

**Issue by SachaTending** [KotMilkMeoWtwo/MeowLandPlugin#5]
при попытке использовать admintool в чате пишет то что аргументов слишком много

**Comment by SachaTending** [comment]
и вообще любой javascript

**Comment by SachaTending** [comment]
+ в чат не выводится результат выполнения команды

**Comment by KotMilkMeoWtwo** [comment]
/js пока не работает. Не доделано. Сегодня/завтра сделаю
