### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by SachaTending** [KotMilkMeoWtwo/MeowLandPlugin#6]
![image](https://user-images.githubusercontent.com/65766775/174275671-48549b7d-e1c5-4010-9f69-3d07917dd040.png)

**Comment by SachaTending** [comment]
[sasha@SMokeOfAnarchy-Server ~]$ java --version
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7)
OpenJDK 64-Bit Server VM (build 17.0.3+7, mixed mode)

**Comment by KotMilkMeoWtwo** [comment]
Попозже посмотрю, что там, а так можно попробовать конфиг перегенирировать

**Comment by SachaTending** [comment]
ну оно сообщения отправляет

**Comment by KotMilkMeoWtwo** [comment]
покажи bot_prefix в конфиге
