### ISSUE TITLE
не работают комманды

### ISSUE THREAD

**Issue by zxsrxt-kebab-case** [KotMilkMeoWtwo/MeowLandPlugin#7]
/spawn когда спавнишь юнитов сообщение в чате просто пропадает визуально, но а в  записи чата видно что сообщение есть, но юниты не спавнятся.
/js не работает, пишет too many arguments
![image](https://user-images.githubusercontent.com/107710425/174350637-995784e3-7ea3-4feb-aec2-d4a96ce17370.png)

**Comment by zxsrxt-kebab-case** [comment]
еще когда пытаешься подобрать предмет на себя вылезает это 
![image](https://user-images.githubusercontent.com/107710425/174351156-e9602b9e-554c-4c4d-b8e7-94daca6ef279.png)
 и не подбирается

**Comment by SachaTending** [comment]
ну это уже мой сервер

**Comment by KotMilkMeoWtwo** [comment]
второе хз, не факт, что из-за меня. дай скрин консоли

**Comment by SachaTending** [comment]
второе как раз мой сервер

**Comment by zxsrxt-kebab-case** [comment]
теперь кикнуло когда менял предмет в сортировщиках
![image](https://user-images.githubusercontent.com/107710425/174351455-7b41bba0-c7b0-4dd3-8ef7-cbc40539bc99.png)

**Comment by KotMilkMeoWtwo** [comment]
хмм

**Comment by KotMilkMeoWtwo** [comment]
покажите, что в консоль срёт

**Comment by zxsrxt-kebab-case** [comment]
мне ничего не высирает

**Comment by SachaTending** [comment]
я конфиг поставил
interactratelimit

**Comment by KotMilkMeoWtwo** [comment]
значит не плагин виноват

**Comment by zxsrxt-kebab-case** [comment]
убери нах этот конфиг

**Comment by SachaTending** [comment]
я убрал

**Comment by KotMilkMeoWtwo** [comment]
> /spawn когда спавнишь юнитов сообщение в чате просто пропадает визуально, но а в записи чата видно что сообщение есть, но юниты не спавнятся. /js не работает, пишет too many arguments ![image](https://user-images.githubusercontent.com/107710425/174350637-995784e3-7ea3-4feb-aec2-d4a96ce17370.png)

ааааааа...... есть вероятность, что уже достигнут лимит юнитов на команду, или у команды, за которую спавнишь, нет ядра

**Comment by zxsrxt-kebab-case** [comment]
пишу /spawn flare 2 sharded, ядро есть таких юнитов нет и не работает

**Comment by KotMilkMeoWtwo** [comment]
хм

**Comment by KotMilkMeoWtwo** [comment]
опять же нужен лог из консоли

**Comment by zxsrxt-kebab-case** [comment]
Опять же у меня нет консоли

**Comment by KotMilkMeoWtwo** [comment]
Кусье пофиксил это (вроде)
